version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end-net
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DBContext=Server=sqlserver,1433;Database=mak;User=sa;Password=YourPassword123!;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
      - MSSQL_DATABASE=mak
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "sqlcmd -S localhost -U sa -P YourPassword123! -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
