services:
  backend:
    build:
      context: ./back-end-net
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:8080" # API exposed here
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=mak;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
